//
//  Quotes.swift
//  Sprinkle of Yeezus
//
//  Created by Eric Bates on 5/20/18.
//  Copyright © 2018 Eric Bates. All rights reserved.
//

import Foundation

struct Sprinkle{
    let quote: String
    let date: Int
    let quoteSource: String
    var timesPicked: Int
}

//Array of structures of Kanye Quotes
var sprinkleList = [Sprinkle(quote: "George Bush doesn't care about black people", date: 2005, quoteSource: "Hurricane Benefit Relief Concert, NBC", timesPicked: 0),
                    Sprinkle(quote: "My greatest pain in life is that I will never be able to see myself perform live.", date: 0, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "Nothing in life is promised except death.", date: 0, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "We all self-conscious. I'm just the first to admit it.", date: 2004, quoteSource: "The College Dropout", timesPicked: 0),
                    Sprinkle(quote: "They say you can rap about anything except for Jesus, that means guns, sex, lies, video tapes, but if I talk about God my record won't get played Huh?", date: 2004, quoteSource: "The College Dropout", timesPicked: 0),
                    Sprinkle(quote: "If you have the opportunity to play this game of life you need to appreciate every moment. a lot of people don't appreciate the moment until it's passed.", date: 2005, quoteSource: "47th Annual Grammy Awards", timesPicked: 0),
                    Sprinkle(quote: "My music isn’t just music — it’s medicine.", date: 2006, quoteSource: "Magazine Inteview with MusicWorld", timesPicked: 0),
                    Sprinkle(quote: "I'll say things that are serious and put them in a joke form so people can enjoy them. We laugh to keep from crying.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I know I got angels watching me from the other side.", date: 2004, quoteSource: "Never Let Me Down (ft Jay Z), The College Dropout", timesPicked: 0),
                    Sprinkle(quote: "People always say that you can't please everybody. I think that's a cop-out. Why not attempt it? Cause think of all the people you will please if you try.", date: 2006, quoteSource: "Telegraph", timesPicked: 0),
                    Sprinkle(quote: "If you can communicate this product you can make money off the product. Look at Gaga. She’s the creative director of Polaroid. I like some of the Gaga songs. What the f*** does she know about cameras?", date: 2013, quoteSource: "BBC Radio 1 Interview", timesPicked: 0),
                    Sprinkle(quote: "I hate when I'm on a flight and I wake up with a water bottle next to me like oh great now I gotta be responsible for this water bottle", date: 2010, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I specifically ordered persian rugs with cherub imagery!!! What do I have to do to get a simple persian rug with cherub imagery uuuuugh.", date: 2010, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "Keep fresh flowers in the crib", date: 2010, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "cool ain't cool no more, it's a new day education is the new motivation truth taste and beauty let's raise our children better than us", date: 2010, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "Don't ask me what I think the best song of last year was, because my opinion is the same as most of America's. It was 'Gold Digger.'", date: 2006, quoteSource: "Rolling Stone", timesPicked: 0),
                    Sprinkle(quote: "'Everything I'm not made me everything I am.' In my humble opinion, that's a prophetic statement. Gandhi would have said something like that.", date: 2007, quoteSource: "Rolling Stone", timesPicked: 0),
                    Sprinkle(quote: "Come on now! How could you be me and want to be someone else?", date: 2005, quoteSource: "Guardian", timesPicked: 0),
                    Sprinkle(quote: "When I think of competition it's like I try to create against the past. I think about Michelangelo and Picasso. You know, the pyramids.", date: 2010, quoteSource: "Slate", timesPicked: 0),
                    Sprinkle(quote: "I am so credible and so influential and so relevant that I will change things.", date: 2013, quoteSource: "New York Times", timesPicked: 0),
                    Sprinkle(quote: "I'm the No. 1 living and breathing rock star.", date: 2013, quoteSource: "W Magazine", timesPicked: 0),
                    Sprinkle(quote: "When someone comes up and says something like, 'I am a god,' everybody says 'Who does he think he is?' I just told you who I thought I was. A god. I just told you. That's who I think I am.", date: 2013, quoteSource: "BBC Radio 1 Interview", timesPicked: 0),
                    Sprinkle(quote: "For me to say I wasn't a genius, I would just be lying to you and to myself.", date: 2013, quoteSource: "Jimmy Kimmel Live", timesPicked: 0),
                    Sprinkle(quote: "I feel like a little bit, like, I'm the Braveheart of creativity.", date: 2013, quoteSource: "San Francisco's 99.7", timesPicked: 0),
                    Sprinkle(quote: "I am Warhol! I am the number one most impactful artist of our generation. I am Shakespeare in the flesh. Walt Disney, Nike, Google.", date: 2013, quoteSource: "Sway in the Morning", timesPicked: 0),
                    Sprinkle(quote: "Visiting my mind is like visiting the Hermès factory.", date: 2013, quoteSource: "W Magazine", timesPicked: 0),
                    Sprinkle(quote: "I'm doing pretty good as far as geniuses go ... I'm like a machine. I'm a robot.", date: 2008, quoteSource: "Tim Westwood", timesPicked: 0),
                    Sprinkle(quote: "The Bible had 20, 30, 40, 50 characters in it. You don't think that I would be one of the characters of today's modern Bible?", date: 2008, quoteSource: "Tim Westwood", timesPicked: 0),
                    Sprinkle(quote: "You can't look at a glass half full or empty if it's overflowing.", date: 0, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I have, like, nuclear power, like a superhero, like Cyclops when he puts his glasses on.", date: 2009, quoteSource: "Details", timesPicked: 0),
                    Sprinkle(quote: "Yeah. I'm rich and I'm famous, but I try not to be extra with it.", date: 2009, quoteSource: "Complex", timesPicked: 0),
                    Sprinkle(quote: "A lot of people were wondering what I was going to do if I didn't win anything. I guess we'll never know.", date: 2005, quoteSource: "47th Annual Grammy Awards", timesPicked: 0),
                    Sprinkle(quote: "This is a gospel album with a whole lotta cursing on it but it's still a gospel album and it's the gospel according to 'Ye.", date: 2016, quoteSource: "Real 92.3 FM, Los Angeles", timesPicked: 0),
                    Sprinkle(quote: "I am offended by the word 'luck.'", date: 2016, quoteSource: "Real 92.3 FM, Los Angeles", timesPicked: 0),
                    Sprinkle(quote: "I have no interest in working with anyone who is too important or too good or too traditional to take a call at 3 a.m.", date: 2016, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "Caught 10,000 retweets in half a second. #facts", date: 2016, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "This is not album of the year. This is album of the life.", date: 2016, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "Being fresh is more important than having money.", date: 2015, quoteSource: "Vanity Fair", timesPicked: 0),
                    Sprinkle(quote: "I think the words \"dreamer\" and \"passionate\" diminish my will to execute. Because to be passionate about something or to dream about something does not say that it was executed.", date: 2015, quoteSource: "Vanity Fair", timesPicked: 0),
                    Sprinkle(quote: "I think if Michelangelo was alive or Da Vinci was alive, there's no way that they wouldn't be working with shoes.", date: 2015, quoteSource: "Vanity Fair", timesPicked: 0),
                    Sprinkle(quote: "When you're the absolute best, you get hated on the most.", date: 2015, quoteSource: "Commencement speech", timesPicked: 0),
                    Sprinkle(quote: "Sweatshirts are (expletive) important. That might sound like the funniest quote ever. How can you say all this stuff about running for president in 2020 and then say sweatshirts are important? But they are. Just mark my words. Mark my words like Mark Twain.", date: 2015, quoteSource: "Vanity Fair", timesPicked: 0),
                    Sprinkle(quote: "Fame is often looked down upon in the design world, so it's actually been something I had to overcome.", date: 2015, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I have millions of ideas and I represent a new generation just trying to express themselves in a broken world.", date: 2015, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "You should only believe about 90 percent of what I say. As a matter of fact, don’t even believe anything that I’m saying at all. I could be completely fucking with you, and the world, the entire time", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "As a man I am flawed, but my music is perfect.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I've reached a point in my life where my Truman Show boat has hit the painting.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "My message isn't perfectly defined. I have, as a human being, fallen to peer pressure.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "Success is the best revenge", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "Kate Upton ain’t Marilyn Monroe, Kim is Marilyn Monroe, you know that.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "Fur pillows are hard to actually sleep on.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I jog in Lanvin.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "Having money isn't everything, not having it is.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I don't even listen to rap. My apartment is too nice to listen to rap in ", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I don't know what's better gettin' laid or gettin' paid.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "We're living the future so the present is our past.", date: 2010, quoteSource: "Monster (ft Jay-Z, Rick Ross, and Nicki Minaj", timesPicked: 0),
                    Sprinkle(quote: "for anyone whose tried to text or call me in the past 2 weeks I got rid of that phone so I could focus on these albums", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "rules are structure for people who can’t carve their own path successfully", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "free thinking is a super power", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I’m hyper focused on the now", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "naps are awesome", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "take a walk outside. Fresh air is healing", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "enjoy the present", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "if you’re in the way of your own life you’ll end up in the way of other people’s lives too", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "most fear is learned", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "love is infinite", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I was chilling with this white girl having a conversation and she cut me off and said... Hold up... I thought you didnt like us?!", date: 0, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "you may be talented, but you're not kanye west", date: 2012, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "Sometimes I get emotional over fonts", date: 0, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I'm ready to get out of my own way. The ego is overdone... it's like hoodies", date: 0, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I hate big ass  striped scarves", date: 0, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "Stevie Wonder never had to use the word bitch to get his point across", date: 0, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I could never do stand up cause I tell jokes better when I'm sitting", date: 0, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "So Nirvana can have a naked human being on they cover but I can't have a PAINTING of a monster with no arms and a polka dot tail and wings.", date: 0, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "sometimes I push the door close button on people running towards the elevator. I just need my own elevator sometimes, my 7 floor sanctuary", date: 0, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "Do you know where to find marble conference tables? I'm looking to have a conference... not until I get the table though", date: 0, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I hate long ass sideburns with the line up RnB beard", date: 0, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "My goal, if I was going to do art, fine art, would have been to become Picasso or greater… That always sounds so funny to people, comparing yourself to someone who has done so much, and that’s a mentality that suppresses humanity…", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "One of my biggest achilles heels has been my ego. And if I, Kanye West, can remove my ego, I think there’s hope for everyone.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I don’t think there’s a living celebrity with more weapons formed against him, but I don’t think there’s one more prosperous.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "So, the voices in my head told me go, and then I just walked up, like, halfway up the stage… But I just didn’t really want to take away from Beck’s moment, or the time he’s having to talk. It was kind of a joke – like the Grammys themselves.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I think what Kanye West is going to mean is something similar to what Steve Jobs means. I am undoubtedly, you know, Steve of internet, downtown, fashion, culture. Period. By a long jump. I honestly feel that because Steve has passed, you know, it’s like when Biggie passed and Jay Z was allowed to become Jay Z.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "Sometimes people write novels and they just be so wordy and so self-absorbed. I am not a fan of books. I would never want a book’s autograph. I am a proud non-reader of books.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I will go down as the voice of this generation, of this decade, I will be the loudest voice.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "One of the problems with being a bubbling source of creativity – it’s like I’m bubbling in a laboratory, and if you don’t put a cap on it, at one point it will, like, break the glass. If I can hone that… then I have, like, nuclear power, like a superhero, like Cyclops when he puts his glasses on.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "There’s nothing I really wanted to do in life that I wasn’t able to get good at. That’s my skill. I’m not really specifically talented at anything except for the ability to learn. That’s what I do. That’s what I’m here for.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I’m a pop enigma. I live and breathe every element in life. I rock a bespoke suit and I go to Harold’s for fried chicken. It’s all these things at once, because, as a taste maker, I find the best of everything.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "People ask me a lot about my drive. I think it comes from, like, having a sexual addiction at a really young age. Look at the drive that people have to get sex – to dress like this and get a haircut and be in the club in the freezing cold at 3 A.M., the places they go to pick up a girl. If you can focus the energy into something valuable, put that into work ethic.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "(About Kim Kardashian) Y’all are acting like this ain’t the most beautiful woman of all time. Wait a second, wait a second – I’m talking about arguably of human existence. The top 10 of human existence… I don’t give a f*ck what type of jacket she got on.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "If you read books – which I don’t, none at all – about how to become a billionaire, they always say, ‘You learn more from your mistakes.’ So if you learn from your mistakes, then I’m a f*cking genius.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I am so credible and so influential and so relevant that I will change things.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I feel like I’m too busy writing history to read it.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I believe that bad taste is vulgar. It’s like cursing. I think the world can be saved through design, because what is the most distasteful thing someone can do? Kill someone. So, good taste is the opposite of that.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "For me, first of all, dopeness is what I like the most. Dopeness. People who want to make things as dope as possible, and, by default, make money from it.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I am in the lineage of Gil Scott-Heron, great activist-type artists. But I’m also in the linage of a Miles Davis, you know, that liked nice things too.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "Just imagine if I woke up one day and I was whack. What would I do then?", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I am the number one human being in music. That means any person that’s living or breathing is number two.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I’m the closest that hip-hop is getting to God. In some situations I’m like a ghetto Pope.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I’m doing pretty good as far as geniuses go…I’m like a machine. I’m a robot. You cannot offend a robot.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I’m going to be the Tupac of clothing.", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I don’t personally like suit jackets anymore. I especially hate suit jackets on women… that was a groundbreaking idea 5 million years ago!", date: 0, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I’ve never been about beef    I’m about love    lines were crossed and it’s not good for anyone    so this is dead now", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "gratitude and happiness best describe what my wife means to me. I’m deeply grateful and purely happy 😊", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "Google dopamine", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "there was a time when we completely operated without phones. We're addicted to our phones.", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "sometimes we all need hugs", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "rules are structure for people who can’t carve their own path successfully", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "free thinking is a super power", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I’m hyper focused on the now", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "naps are awesome", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "take a walk outside. Fresh air is healing", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "enjoy the present", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "if you’re in the way of your own life you’ll end up in the way of other people’s lives too", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "most fear is learned", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "stop thinking about things for a long time without saying what you think", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "love is infinite", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "Try to avoid repetition do meetings in different places and at different times than the normal break the normal", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "today is the best day ever and tomorrow's going to be even better", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "Trust your feelings. Stop thinking so much", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I no longer have a manager. I can't be managed", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I’ve always had a desire to do things people wouldn’t even think to do", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "practice pure love", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "question everything", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "be fearless. Express what you feel not what you've been programmed to think.", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "all you have to be is yourself", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "it's not where you take things from. It's where you take them to", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "if you wanna see the true character of person watch the way they treat someone who can't do anything for them.", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "truth is my goal. Controversy is my gym. I'll do a hundred reps of controversy for a 6 pack of truth", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "don't trade your authenticity for approval", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "Cars have four wheels. Hoodies have hoods. It's amusing to me when some one says this is an original hoodie. Bro... it's a hoodie 🤷‍♂️", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "everything you do in life stems from either fear or love", date: 2018, quoteSource: "", timesPicked: 0),
                    Sprinkle(quote: "I don't take advice from people less successful than me", date: 2018, quoteSource: "Ye", timesPicked: 0),
                    Sprinkle(quote: "sometimes I have trouble saying no because I want to help everyone", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I killed my ego", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "give without pride", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "your pride can be and will be used against you", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I be taking naps", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I always misspell genius SMH! The irony!", date: 2010, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "There's love stories. Pain happiness. It's 3 dementional. There's taste touch sound. It's the most entertaining for of entertainment. Just being. We believe time is a man made construct. Actually time and money are both man made currency. Because you can spend them both.", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I make awesome decisions in bike stores!!!", date: 0, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I open the debate... The 2nd verse of New Slaves is the best rap verse of all time....meaning...OF ALL TIME IN THE HISTORY OF RAP MUSIC, PERIOD", date: 2013, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I'M SO HYPE RIGHT NOW  EVERYTHING HAS CHANGED ... HAVE YA'LL EVER SEEN TRON? THE END OF THE TRON WHERE EVERYTHING LIGHT UP!!!!", date: 2016, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "Have you ever thought you were in love with someone but then realized you were just staring in the mirror for 20 minutes?", date: 2014, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "Man... ninjas are kind of cool... I just don't know any personally", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I'm not even gon lie to you. I love me so much right now.", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "You have distracted from my creative process", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "Man... whatever happened to my antique fish tank?", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I BEEN FLY SO LONG I FELL ASLEEP ON THE PLANE!", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "Please: Do everything you possibly can in one lifetime.", date: 2015, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I hope you have a nice weekend.", date: 2016, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "Exes can be mad but just know I never let them play with my ass… I don’t do that… I stay away from that area all together", date: 2016, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "All y'all so worried about being likable but only a few are concerned about being great!!!", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I’m this generation's Disney… I want to bring dope shit to the world…", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I have discovered my single greatest quality. I care.", date: 2018, quoteSource: "Twitter", timesPicked: 0),
                    Sprinkle(quote: "I just threw some kazoo on this bitch", date: 2013, quoteSource: "Interview with MTV", timesPicked: 0),
                    Sprinkle(quote: "How many m*****f***ers you done seen with a leather jogging pant?", date: 2013, quoteSource: "Zane Lowe interview", timesPicked: 0),
                    Sprinkle(quote: "What if Kanye made a song about Kanye/Called \"I Miss the Old Kanye\"? Man that'd be so Kanye", date: 2018, quoteSource: "I love kanye - TLOP", timesPicked: 0),
                    Sprinkle(quote: "On one end, I try to scale it back because I don’t want to close any of the doors needed to create the best product possible. But my ego is my drug. My drug is, ‘I’m better than all you other mother fuckers. Kiss my ass!", date: 2013, quoteSource: "W magazine interview", timesPicked: 0),
                    Sprinkle(quote: "I can’t let these people play me. Name one genius that ain't crazy", date: 2016, quoteSource: "Feedback - The Life of Pablo", timesPicked: 0),
                    Sprinkle(quote: "I care. I care about everything. Sometimes not giving a fuck is caring the most", date: 2013, quoteSource: "W magazine interview", timesPicked: 0),
                    Sprinkle(quote: "I’m not comfortable with comfort. I’m only comfortable when I’m in a place where I’m constantly learning and growing", date: 2013, quoteSource: "W magazine interview", timesPicked: 0),
                    Sprinkle(quote: "Mayonnaise-color Benz, I push Miracle Whips", date: 2004, quoteSource: "Last Call - The College Droupout", timesPicked: 0),
                    Sprinkle(quote: "I ain’t no muthafuckin celebrity. I ain’t runnin’ for office. I ain’t kissin’ nobody’s muthafuckin babies. I drop your baby and you muthafuckin sue me and shit", date: 2013, quoteSource: "Adult Swim Upfront at New York's Roseland Ballroom", timesPicked: 0),
                    Sprinkle(quote: "And I was almost famous, now everybody love Kanye; I’m almost Raymond", date: 2004, quoteSource: "Last Call - The College Dropout", timesPicked: 0),
                    Sprinkle(quote: "If you have the opportunity to play this game called life, you have to appreciate every moment. A lot of people don't appreciate their moment until it's passed", date: 2005, quoteSource: "Grammy Acceptance Speech", timesPicked: 0),
                    Sprinkle(quote: "Know your worth! People always act like they're doing more for you than you're doing for them", date: 2009, quoteSource: "Thank you and You're Welcome book", timesPicked: 0),
                    Sprinkle(quote: "I have absolutely no plans for what I'm going to say", date: 2015, quoteSource: "FN Achievement Awards Acceptance Speech", timesPicked: 0),
                    Sprinkle(quote: "I hate the way they portray us in the media. If you see a black family it says they're looting, if you see a white family it says they're looking for food", date: 2005, quoteSource: "Huricane Katrina relief concert", timesPicked: 0),
                    Sprinkle(quote: "I refuse to accept other people's ideas of happiness for me. As if there's a 'one size fits all' standard for happiness", date: 2009, quoteSource: "Thank You and You're Welcome book", timesPicked: 0),
                    Sprinkle(quote: "Do you see this COAT?!", date: 2015, quoteSource: "Paparazzi exchange", timesPicked: 0),
                    Sprinkle(quote: "Would you believe in what you believe in if you were the only one who believed it?", date: 2009, quoteSource: "Thank You and You're Welcome book", timesPicked: 0),
                    Sprinkle(quote: "HOW SWAY?!", date: 2013, quoteSource: "Sway in the Morning", timesPicked: 0),
                    Sprinkle(quote: "I have this table in my new house. It was some weird nouveau-riche marble table, and I hated it. We would try to set up different things around it, but it never really worked. I realized that table was my ego. No matter what you put around it, under it, no matter who photographed it, the douchebaggery would always come through.", date: 2015, quoteSource: "New York Times Interview", timesPicked: 0),
                    Sprinkle(quote: "People always say that you can't please everybody. I think that's a cop-out. Why not attempt it? 'Cause think of all the people you will please if you try", date: 2006, quoteSource: "The Guardian Interview", timesPicked: 0),
                    Sprinkle(quote: "People ask me a lot about my drive. I think it comes from, like, having [an intimate] addiction at a really young age. Look at the drive that people have to get [lucky]—to dress like this and get a haircut and be in the club in the freezing cold at 3 a.m., the places they go to pick up a girl. If you can focus the energy into something valuable, put that into work ethic.", date: 2013, quoteSource: "Vulture interview", timesPicked: 0),
                    Sprinkle(quote: "I get to represent somebody I don’t think is getting represented right now. The regular dude: the guy who believes in God but still likes pussy. You know what I mean?", date: 2003, quoteSource: "The Fader", timesPicked: 0),
                    Sprinkle(quote: "I'm the rap version of Dave Chappelle. I'm not sayin' I'm nearly as talented as Chappelle when it comes to political and social commentary, but like him, I'm laughing to keep from crying", date: 2004, quoteSource: "Rolling Stone", timesPicked: 0),
                    Sprinkle(quote: "Dog, VIBE only gave my album a 4! I know my shit is better than a 4. A horrible album with just ‘Jesus Walks’ on it is a 4! C’mon dog, the demo version was a 5! You need to rate it again, but you’ll have to create a new rating system.", date: 2004, quoteSource: "Vibe", timesPicked: 0),
                    Sprinkle(quote: "Someone could be a better rapper, dance better. But culturally impacting? When you look back at these four and a half years, who's the icon at the end of the day? Who broke down color barriers? What other black guy would a white person use as a fashion reference?", date: 2009, quoteSource: "Details", timesPicked: 0),
                    Sprinkle(quote: "Anyone who doesn't give [The College Dropout] a perfect score is lowering the integrity of the magazine", date: 2005, quoteSource: "Guardian", timesPicked: 0),
                    Sprinkle(quote: "I don't like walking around with people thinking I'm doing cool shit, because there's nothing I'm doing that's uncool", date: 2014, quoteSource: "GQ", timesPicked: 0),
                    Sprinkle(quote: "I like T-shirts and women in yoga pants… I live in LA that’s what some people wear… not sure why someone would put a suit jacket with that.", date: 0, quoteSource: "", timesPicked: 0)
]


